name: Deployment 
on:
  push:
    branches:
      - main
  workflow_dispatch:
               
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy application
        run: echo "Deploying application..." 
        # Add your deployment commands here